variable "cluster_name" {}
variable "task_def_name" {}
variable "task_def_rev" {}
variable "data_task_def_rev" {}
#variable "alb_arn" {}
variable "tg_arn" {}
variable "alb_listener_rule" {}
variable "iam_service_role" {}
#variable "container_name" {}